### ISSUE TITLE
Project status/future?

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/maze-runner-server#1]
Hey Bartosz--great README! Wondering what the future of this project is--seems like it has potential to be useful outside of Zalando...

**Comment by bocytko** [comment]
This project has been used during a job fair as a competition task. We also used it internally during coding dojos.

**Comment by LappleApple** [comment]
@bocytko Do you mind if I move this repo to here, until we find time to improve the README? 

https://github.com/Zalando-Incubator

It will remain public, just not on the main Zalando org.

**Comment by bocytko** [comment]
@LappleApple sure, you can move the repo to the incubator.

**Comment by LappleApple** [comment]
@bocytko Thanks! It's over here now :)
